networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/ect/nginx/nginx.conf'
    depends_on:
      - telegramm_okna
    networks:
      - dev

  backend:
    build:
      context: ./telegramm_okna

      